### ISSUE TITLE
Trigger Rendering Issue under Triton Theme

### ISSUE THREAD

**Issue by pgodwin** [extnet/examples5.ext.net#1]
See rendering on http://examples.ext.net/#/Form/Triggers/Trigger_Icons/

![image](https://cloud.githubusercontent.com/assets/1046558/12907833/d9125cac-cf3b-11e5-9deb-1bae14e92f60.png)

**Comment by DaniilVeriga** [comment]
Thank you for the report! That is a known issue that should fixed in the 4.0 beta which should happen soon.
https://github.com/extnet/Ext.NET/issues/1247

**Comment by DaniilVeriga** [comment]
The issue has been fixed - the icons are displayed correctly now. It will be fixed online with the upcoming release. 

Though, TriggerIcons are still needed to be reviewed for better consistency with all non-classic themes. Created extnet/Ext.NET#1279.
