### ISSUE TITLE
Example DatePicker overview glitches when using browser zoom functionality

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/examples5.ext.net#14]
Found: 4.2.0
This was reported on this Ext.NET forum thread: [DateField Picker Month & Year Not showing properly](https://forums.ext.net/showthread.php?61909)
There's a Sencha forum thread complaining of the same thing: [Datefield browser zoom out to 90% messes up Month/Year picker](https://www.sencha.com/forum/showthread.php?302617)

Sencha states browser zooming is not supported by ExtJS at all on that thread, so that's one thing not going to be fixed.

But in the same thread somebody posted a CSS override that fixes this, and this can be applied to our example as well as a sample fix for that.

**Comment by rkganapathy** [comment]
This is not support for IE 8
